server:
  bind_port: 8080
  grace_exit_timeout: 10

log:
  file_name: "app.log"
  max_size: 100
  max_backups: 5
  max_keep_days: 30
  compress: true

database:
  driver: sqlite3
  database: echodb.sqlite
  max_idle: 10
  max_open: 10